---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dreadnought.
--- DateTime: 16/05/2022 23:29
---
import "utility"

class("Enemy").extends()


class("Fly").extends()

function Fly:init(x,y)
    local flyImage = playdate.graphics.image.new("images/fly.png")
    local flySprite = playdate.graphics.sprite.new(flyImage)
    flySprite:add()
    flySprite:setImageFlip(playdate.geometry.kFlippedX)
    flySprite:moveTo(x,y)
    self.sprite = flySprite
    self.x = x
    self.y = y
    self.w = 20
    self.h = 20
    self.collisionRect = Rect(x,y,20,20)

    self.cycle = 0 -- as this increases, fly moves according to its strategy

end


function Fly:update()
    self.cycle = self.cycle + 1
    self.x = self.x - 0.6
    self.sprite:moveTo(self.x,self.y)

    if(self.x< -10 or self.x>410) then
        self:setVisible(false)
    end


end

function Fly:enter()
    local y = math.random(10)
    self.sprite:moveTo(400,y*10+50)
    self.x = 400
    self.y  = y*20
    self.sprite:setVisible(true)
end

function Fly:setVisible(b)
    self.sprite:setVisible(b)
end

function Fly:getVisible()
    return self.sprite:isVisible()
end

function Fly:hit(x,y)
    return Rect(self.x-10 ,self.y-10 ,20,20):contains(x,y)
end

