---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dreadnought.
--- DateTime: 03/06/2022 20:39
---
import "CoreLibs/graphics"
import "CoreLibs/object"


class("Game").extends()

function Game:init()


end


function Game:update()

end

function Game:draw()

end