---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dreadnought.
--- DateTime: 03/06/2022 20:50
---
import "CoreLibs/graphics"
import "CoreLibs/object"

class("Point").extends()

function Point:init(x,y)
    self.x = x
    self.y = y
end


class("Rectangle").extends()

function Rectangle:init(x,y,w,h)
    self.left = x -- left
    self.top = y -- top
    self.w = w
    self.h = h
    self.right = self.left + self.w
    self.bottom = self.top + self.h
end


function Rectangle:contains_point(p)
    if p.x >= self.left and p.x <= self.right  and p.y >= self.top and p.y <= self.bottom then
        return true
    else
        return false
    end
end