---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dreadnought.
--- DateTime: 04/06/2022 13:19
---

tool_offset_x = 30
tool_offset_y = 0
game_area_width  = 320
horizontal_button_sensitivity = 1
crank_vertical_sensitivity = 0.2
