---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dreadnought.
--- DateTime: 04/06/2022 16:06
---


import "CoreLibs/object"


class("List").extends()

function List:init()
    self.vals = {}
    self.size = 0
end

function List:append(v)
    self.vals[self.size+1] = v
    self.size = self.size + 1
end

function List:clear()
    self.vals = {}
    self.size = 0
end

function List:removeAt(i)
    local v = self.vals[i]
    for j = i,self.size do
        self.vals[j] = self.vals[j+1]
    end
    return v
end

function List:iterate(f)
    for i = 1,self.size do
        f(self.vals[i])
    end
end

function List:map(f)
    local l  =List()
    for i = 1,self.size do
        l:append(f(self.vals[i]))
    end
    return l
end

function List:get(x)
    return self.vals[x]
end

function List:contains(n)
    local b = false
    for i = 1,self.size do
        if self.vals[i] == n then
            b = true
            break
        end
    end
    return b

end