---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dreadnought.
--- DateTime: 16/05/2022 19:09
---



function horizontalButton()
    local rightDown = playdate.buttonIsPressed(playdate.kButtonRight)
    local leftDown = playdate.buttonIsPressed(playdate.kButtonLeft)
    local deltaX = 0
    if(rightDown)then
        deltaX = 1
    end
    if(leftDown) then
        deltaX = deltaX-1
    end
    return deltaX
end

function verticalButton()
    local upDown = playdate.buttonIsPressed(playdate.kButtonUp)
    local downDown = playdate.buttonIsPressed(playdate.kButtonDown)
    local deltaY = 0
    if(upDown)then
        deltaY = 1
    end
    if(downDown) then
        deltaY = deltaY-1
    end
    return deltaY
end


class("Rect").extends()

function Rect:init(x,y,w,h)
    self.x = x
    self.y = y
    self.w = w
    self.h = h
end

function Rect:contains(x,y)
    return self.x < x and self.x + self.w > x and self.y < y and self.y + self.h > y
end